// unit tests for countBy
// Validate that countBy correctly counts occurrences of keys generated by an iteratee function
// countBy is useful for aggregating data, such as counting active vs inactive users

import countBy from '../countBy.js'

describe('countBy', () => {

  // Shared test data for multiple tests
  const users = [
    { user: 'barney', active: true },
    { user: 'betty',  active: true },
    { user: 'fred',   active: false },
  ]

  // this test fails ,the first occurrence of each key is initialized to 0 instead of 1,
  // causing all counts to be off by one
  test('counts occurrences based on a simple property', () => {
    const result = countBy(users, value => value.active)
    expect(result).toEqual({ true: 2, false: 1 })
  })

  // fails for the same reason (off by one issue)
  test('counts users by active status', () => {
    const result = countBy(users, value => value.active)
    expect(result).toEqual({ true: 2, false: 1 })
  })


  test('handles empty collections', () => {
    const result = countBy([], value => value)
    expect(result).toEqual({})
  })

  // Also fails due to the same off-by-one bug when grouping values by string length
  test('groups strings by length', () => {
    const values = ['one', 'two', 'three', '']
    const result = countBy(values, value => value.length)
    // length 0: '', length 3: 'one','two', length 5: 'three'
    expect(result).toEqual({ 0: 1, 3: 2, 5: 1 })
  })

  test('returns an empty object for an empty array', () => {
    const result = countBy([], value => value)
    expect(result).toEqual({})
  })

  // Fails, demonstrates that the same bug appears when iterating over object values
  // instead of arrays
  test('works with object collections (iterating over values)', () => {
    const collection = { a: 1, b: 2, c: 1 }
    const result = countBy(collection, value => value)
    expect(result).toEqual({ 1: 2, 2: 1 })
  })

    // This one fails too, documents how countBy should behave when counting occurrences
    // The current implementation returns { 1: 1, 2: 0 } instead
  test('starts counts at 1 for the first occurrence of each key (expected behaviour)', () => {
    const result = countBy([1, 1, 2], value => value)
    expect(result).toEqual({ 1: 2, 2: 1 })
  })
})
