@startuml buyer
title Activity diagram for buyer
start
group Browse
:User opens webstore;
while (Done browsing?) is (no)
    :User searches for products;
    :User adds product to cart;
endwhile (yes)
end group

group Cart
:User opens cart;
if (User wants to buy?) then (yes) 
    else(no)

        :Cart saved for next time;
        stop
endif
end group

group Payment
repeat :User in cart;
:User goes to pay;
backward: User is taken back to cart;
repeat while (Payment is succesfulf?) is (no)
->yes;
:Order is placed;
end group
stop
@enduml